package dev.GrubMarker.foodtruck;

public enum FoodType {
    MEXICAN, ORIENTAL, AMERICAN, ITALIAN,AFRICAN, INDIAN, MEDITERRANEAN, FAST_FOOD, DESSERTS, DRINKS, SOUL_FOOD, SEAFOOD, BBQ, VEGAN, VEGETARIAN, GLUTEN_FREE, KOSHER, HALAL, ORGANIC, OTHER
}
